
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - thatchd.io
  resources:
  - testcases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - thatchd.io
  resources:
  - testcases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - thatchd.io
  resources:
  - testsuites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - thatchd.io
  resources:
  - testsuites/status
  verbs:
  - get
  - patch
  - update
