# permissions for end users to edit testcases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testcase-editor-role
rules:
- apiGroups:
  - testiong.thatchd.io
  resources:
  - testcases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testing.thatchd.io
  resources:
  - testcases/status
  verbs:
  - get
