apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: teststatuses.thatchd.io
spec:
  group: thatchd.io
  names:
    kind: TestStatus
    listKind: TestStatusList
    plural: teststatuses
    singular: teststatus
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TestStatus is the Schema for the teststatuses API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TestStatusSpec defines the desired state of TestStatus
            type: object
          status:
            description: TestStatusStatus defines the observed state of TestStatus
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
